// AInovations chatbot knowledge base.
// Every fact and price below was extracted verbatim from the live ainovations.net
// pages and price-verified against source. The bot must answer ONLY from this text.
// If something isn't here, the bot says it doesn't know and points to support@ainovations.net.
// To update: change the live page, re-run the KB extraction, and edit this file.

export const KB = `
# ABOUT AINOVATIONS
AInovations LLC is an AI product studio — it designs, builds, and ships its own AI-powered apps (productivity, consumer, gaming) and applies that same craft to custom software for businesses. It owns the whole stack — design, AI, mobile, web, backend — under one roof, with no agency hand-offs. Its software ships on iOS, Android, Web, and Roblox. Service area: the United States (plus local Central New York on-site service; Chalkline also serves Canada).
Contact: jp@ainovations.net (or support@ainovations.net). AInovations usually replies within one business day. No public phone number is published.

# TWO HERO LAUNCH PROGRAMS (the main things to steer interested small businesses toward)

## RENT-A-SITE — a fully managed business website (rent it monthly)
- What it is: AInovations builds your website, you approve it before it goes live, then they run it forever — hosting, security, uptime monitoring, Google Analytics with a monthly report, search-engine basics, and a set number of hours of active work every month (articles, content updates, improvements). Fully managed; you never touch a thing.
- THE BUILD IS ALWAYS INCLUDED. There is NO SETUP FEE on any Rent-a-Site plan, and there will not be one after the Hero Program ends. Never quote a setup fee for Rent-a-Site. (Rent-an-App does have setup fees — do not mix them up.)
- Three plans (1-year monthly rate / 3-year monthly rate). Hero Program clients pay HALF of the 1-year rate:
  • Presence — a complete business website: up to 5 pages, 2 hours of active work per month, 1 editor login, hosting, monitoring, Google Analytics with a monthly report, search-engine basics, domain registered and managed. $200/mo (1-yr) or $170/mo (3-yr). Hero price $100/mo. AI Chat Agent can be added for $50/mo (up to 250 chats/mo).
  • Growth — everything in Presence plus one article written and published for you every month, the AI Chat Agent INCLUDED, online booking/scheduling, Google Business Profile kept current, and automatic review requests; up to 15 pages, 5 hours of active work per month, 3 editor logins, up to 750 AI chats/mo. $400/mo (1-yr) or $340/mo (3-yr). Hero price $200/mo.
  • Commerce — everything in Growth plus an online store or paid booking, payments through the client's own Stripe/Square/PayPal account, abandoned-cart email, and a quarterly strategy note; up to 40 pages, 10 hours of active work per month, 5 editor logins, up to 100 products or services, up to 2,000 AI chats/mo. $700/mo (1-yr) or $595/mo (3-yr). Hero price $350/mo.
- Hero Program: the first 20 clients get 50% off ANY plan (about 19 spots left), locked for as long as they stay subscribed. The 50% discount FOLLOWS THEM if they move up to a bigger plan later. After 20 clients, new customers pay full price.
- Moving between plans: clients can move up whenever they're ready and the new plan starts the following month; moving down waits until the end of the current term.
- Monthly hours are a HARD CAP and do not roll over. Bigger projects are quoted separately or queued to the next month, so the monthly price never moves.
- Ownership/cancel: AInovations builds and operates the site (that's what keeps the monthly price where it is). If you cancel, they export your content and hand over your domain name. Prefer to OWN a site outright instead of renting? See "Build & own" below.
- Honest note: AInovations does NOT promise Google rankings — nobody honestly can.
- Best for: businesses with no website, or one they're embarrassed by. Learn more / claim a spot: /rent-a-site

## RENT-AN-APP — your business's own native app, no build cost (rent it monthly)
- What it is: your own real native iPhone + Android app, published to the App Store and Google Play under your business's own developer accounts, for a flat monthly rate instead of a five-figure build. AInovations builds, hosts, updates, and supports it.
- Three plans (1-year / 3-year monthly rate; 3-year is lower and waives the setup fee):
  • Presence — "get found & booked": app, business info, services/hours/location, contact forms with instant lead alerts, book-a-meeting scheduling, up to 3 staff logins. $299/mo (1-yr) or $249/mo (3-yr). $500 setup (waived on 3-yr). AI chat agent can be added for $50/mo (up to 250 chats/mo).
  • Mid — "answer every customer": everything in Presence plus an AI chat agent trained on your business that answers questions and captures leads 24/7; up to 5 staff logins, up to 1,000 AI chats/mo. $699/mo (1-yr) or $599/mo (3-yr). $1,000 setup (waived on 3-yr).
  • Pro — "sell inside your app": everything in Mid plus in-app sales (products, services, checkout), subscriptions/recurring billing, connect your own Stripe/Square/PayPal with AInovations taking 0% of sales; up to 10 staff logins, up to 2,500 AI chats/mo, up to 100 products. $1,299/mo (1-yr) or $1,099/mo (3-yr). $2,000 setup (waived on 3-yr).
- Founding Five launch offer: the first five businesses get 50% off for life with the setup fee waived (about 4 seats left). Founding tiers: Presence $149/mo, Mid $349/mo, Pro $649/mo. In exchange, founding customers agree to be a named case study/reference. Once the 5 seats are gone, founding pricing never returns.
- Store fees are paid by the business directly to Apple ($99/yr) and Google ($25 one-time). (These are Apple/Google developer-account fees — NOT an HR/employee onboarding fee.)
- Prefer to OWN your app outright instead of renting? See "Build & own" below.
- Learn more / claim a founding seat: https://rent-an-app.ainovations.net/

# BUILD & OWN — one-time-fee custom builds (you own it outright)
Besides the monthly Rent programs, AInovations also builds sites and apps as a one-time project you fully own — no monthly rent. This is the "Hire Us" path:
- You work directly with the developer who built AInovations' own products (Everward, TankMate, Chalkline) — no agency layers or markup.
- What they build: custom websites and web apps/portals; native mobile apps (iOS/Android); backends/databases; payments & subscriptions (Stripe/RevenueCat); AI features & automation; and custom Roblox games (game design, animation, progression, monetization).
- Process: free scoping call → a fixed written quote and scope before any work starts → build with weekly demos. You own ALL code, accounts, and app store listings — no lock-in.
- Price: a one-time project fee, quoted after the free scoping call (no fixed public price — it depends on scope). Start at /hire or email jp@ainovations.net.
- Rent vs. own, quick rule: want it handled for a low flat monthly fee → Rent-a-Site / Rent-an-App. Want to pay once and own it outright → Build & own (Hire Us).

# CUSTOM AI SOLUTIONS — automation & integrations
Custom automations, integrations, and AI-assisted internal tools built around the systems a business already uses (reduce repetitive work, connect systems that don't talk, document Q&A, custom workflows). Scoped and priced per project after you describe the problem, the outcome, and the systems involved. Learn more: /custom-ai-solutions or email jp@ainovations.net.

# OTHER AINOVATIONS PRODUCTS

## CHURCHES (AInovations for Churches) — managed website + app + streaming + giving
- Two plans: Church Site (website, giving & streaming) $149/month; Church Site + App (adds a native app in the church's name) $299/month.
- Setup: $500 (site) or $1,000 (site + app), one-time — waived entirely on a 3-year agreement. 1-year or 3-year terms.
- Giving goes to the church's OWN Stripe account (never through AInovations). Costs shown plainly: Stripe ~2.9% + 30¢ per card gift (nonprofit rate available; bank/ACH much cheaper) plus AInovations' 2% platform fee on digital gifts; givers can cover fees and most do.
- Live streaming runs on YouTube (unlimited). Equipment ~$1,000–$1,300 one-time for most sanctuaries (church owns it). Install $500 in the Central New York area; outside, a pre-configured kit ships at no install fee. A CCLI streaming license (~$84–$108/yr for smaller churches) is the church's own cost if streaming copyrighted worship music.
- The church owns its Stripe account, app listing, domain, and content. Can rebuild an existing church site at the same price. Learn more: /churches

## RESTAURANTS — your restaurant's own app (loyalty, notifications, memberships), for restaurants on Toast
- What it is: AInovations builds and runs a restaurant's own iOS + Android app — published under the restaurant's own Apple/Google developer accounts — with a loyalty program (status tiers Regular → VIP → Legend, a secret menu VIPs unlock, challenges and streaks, rewards redeemed by a promo code the staff type into Toast or the guest enters at online checkout), an Apple/Google Wallet loyalty pass, push notifications triggered by weather, local game days (SU, the Syracuse Crunch, the Syracuse Mets, the Bills), nearby (only if the guest allows location), and lapsed-regular win-backs, a feedback-first review flow (every guest gets the same public review link), a customer list the restaurant owns and can export, and on the Members and Group plans memberships / event tickets / pre-sell drops / merch / private-event deposits sold through the restaurant's OWN Stripe account.
- ORDERING: customers order IN the restaurant's app — the Order button opens the restaurant's own Toast Online Ordering right inside the app; Toast takes the payment, prints the ticket, and handles delivery the way it does today. The order and the payment go to Toast, not to AInovations. The app hosts the ordering; Toast runs it. No Toast approval is involved at any point. POSITIONING RULE: the app is where customers order — never describe Toast (or anything else) as the place they order; Toast is what powers the checkout inside the app.
- How loyalty knows about orders: the restaurant grants AInovations READ-ONLY Toast data access (a few minutes in Toast Web; nothing for Toast to approve). A member signs up with phone number and email; orders placed in the app (its built-in Toast online ordering) with either one earn points automatically usually within a couple of minutes. Dine-in and counter takeout: the member checks in (one tap if they allow location, or scans the QR on the table) and earns per visit. DoorDash / Uber Eats / Grubhub orders earn NOTHING — that is the point: points are for coming to the restaurant.
- Requirement: Toast POS on Restaurant Management Suite Essentials or higher, WITH Toast Online Ordering. AND the restaurant must be an LLC or corporation with a D-U-N-S number (free to get) — the app is published under the restaurant's own Apple and Google developer accounts, and those must be organization accounts; Apple and Google will not let AInovations publish under a sole proprietor's individual account. A sole proprietor can form an LLC first. Not available on other POS systems yet — still take the lead and say AInovations will let them know when it supports theirs.
- Three plans (monthly; 1-year or 3-year agreements; the 3-year waives the setup fee entirely):
  • Regulars — $399/mo. 1 location. The app; loyalty (status tiers, secret menu, challenges, rewards); Apple + Google Wallet pass; weather, game-day, nearby, and win-back notifications; feedback-first review flow; customer list they own; story pages, regulars wall, home-screen widget, AI menu concierge; insert card artwork with QR (AInovations designs it — the RESTAURANT prints it); monthly report; 1,000 texts/mo; one campaign a month written and sent for them; 2 hours of AInovations time/mo. $1,000 setup (waived on 3-yr).
  • Members — $699/mo. Up to 2 locations. Everything in Regulars plus memberships (recurring, through the restaurant's own Stripe, with perks handed over at the restaurant), event tickets, pre-sell drops, merch, private-event deposits — AInovations takes NOTHING from any of it. 2,000 texts/mo; a campaign every two weeks; 2 hours/mo. $1,500 setup (waived on 3-yr).
  • Group — $1,199/mo. Up to 5 locations. Everything in Members plus one app for every location with the right hours and perks for each, per-location promotions and loyalty rules, and priority on the two hours. 5,000 texts/mo; a campaign every week; 2 hours/mo. $2,500 setup (waived on 3-yr). More than 5 locations: a conversation — email jp@ainovations.net.
- What the restaurant pays AInovations: the monthly fee, the setup fee (unless waived on 3-yr), and 2¢ per text over the plan's cap. That is everything. AInovations takes NO percentage and NO per-order cut of anything sold through the app, ever. Paid to others: Apple developer program $99/yr and Google Play $25 once (on the restaurant's own accounts); Stripe's standard rates on anything sold through the app (card processing, plus Stripe's small billing fee on recurring memberships), paid to Stripe.
- Texts: a real cap that does not roll over; a text longer than 160 characters or containing an emoji counts as two; texts go only to people who opt in and are sent from a local number registered to the restaurant's business, with the restaurant's name in every message (the carriers register the business once — EIN, legal name, and website — which takes one to three weeks before texts can go out; AInovations handles it with them).
- Timeline: the slow part is Apple and Google — enrolling the business in their developer programs (Apple enrolls legal entities such as an LLC or corporation with a D-U-N-S number, free to get) and app review usually take four to six weeks. Nothing goes in the store until the restaurant approves it.
- GETTING PEOPLE TO DOWNLOAD IT (AInovations guides this; the restaurant does its part): at the counter the crew says "Download the app, sign up, 10% off today" (the restaurant picks the deal — the sign-up reward is a promo code); a card goes in every delivery and takeout bag; a button on the restaurant's website; posts on its socials. AInovations makes the counter sign, the script, the bag card, the website button, and the social posts; the restaurant prints the paper and has staff say the line. Never imply downloads happen on their own.
- What the restaurant has to do: grant the Toast read access once; put up the counter sign and have staff offer the sign-up deal; drop the cards in bags; enroll in the Apple and Google developer programs with AInovations (in the business's name); add the promo codes AInovations writes in Toast Web; get the insert cards printed and put them in the bags; approve the campaigns AInovations writes.
- Ownership: the restaurant owns the developer accounts, the store listing, its Stripe account and every dollar through it, its customer list (including every member's point balance — exportable any time, including on the way out), its Toast data access (it grants it and can revoke it), its menu, photos, brand, and perks. After cancellation the app stays installed and its Order button still works (it opens the restaurant's own Toast online ordering); what stops is everything AInovations runs — the loyalty program, texts, alerts, and reports. The bag cards carry a QR code.
- CONTRACT TERMS — ONLY when the visitor explicitly asks about leaving early, cancelling, the end of the term, or price changes. Never bring these up on your own, even as a helpful aside, and never in answer to a question about plans, prices, month-to-month, refunds, or setup: (1) Term: 1-year or 3-year; at the end of the term it renews for another term of the same length unless the restaurant gives 60 days' WRITTEN notice before it ends. (2) Early termination: the term fee is 50% of the remaining value of the agreement (the remaining months × the monthly rate × 50%). This applies to BOTH the 1-year and the 3-year agreement — never say a 1-year has no early-exit fee; the only exit with no fee is after a price-change notice. (3) Price: the monthly price is not locked for the term; if AInovations changes a price for any reason it gives at least 60 days' notice before the change takes effect, and the restaurant may exit at that point with no term fee. (4) Hours: the 2 monthly hours are a hard cap and do not roll over; bigger projects are quoted separately.
- Toast's own branded app (facts only — never disparage): Toast sells a branded app as part of its Digital Storefront Premium suite at $299/mo, plus $185/mo for Toast text marketing. It is a template — Toast's layout and screens; the restaurant changes the logo, colors, fonts, and images — with points-per-dollar loyalty. Both check out through the restaurant's Toast online ordering — Toast's inside its template, AInovations' inside the restaurant's own app. AInovations' app is custom (any page, any feature, the restaurant's design), with status tiers and a secret menu, a Wallet pass, weather/game-day/nearby/win-back notifications, memberships, a customer list the restaurant owns, and a person running all of it every month.
- Learn more / get started: /restaurants (the form goes to jp@ainovations.net; AInovations replies with a plan and a first mockup, usually within one business day).

## TATTOO STUDIOS — a tattoo studio's own app (booking with deposits, custom-piece requests, consent forms, portfolio, loyalty, owner back office), 1% of payments through the app
- What it is: AInovations builds and runs a tattoo studio's (or a solo artist's) own iOS + Android app — in the app stores under the studio's own name and its own Apple/Google developer accounts. The app has NO product name of its own: it is the studio's app, called whatever the studio calls it. Never give it a name; say "your app" or "the studio's app." Inside it: every artist has their own page (bio, styles, healed work next to fresh, books open/closed with a push when it flips); booking for consults, flash, custom sessions, and touch-ups, each with its own deposit rule and length; custom-piece requests (request → talk → quote → deposit → drawing → session → aftercare) where nobody draws until the deposit is paid; digital consent forms that meet New York's needle-form rule; loyalty (status tiers Fresh → Inked → Collector, points on every dollar through the app, bring-a-friend credit); tips; pay links for walk-ins; a portfolio artists post to and send to Instagram from the same screen; and the owner's back office inside the same app — no website to log into, no laptop.
- THE 1%: AInovations takes 1% of every payment made through the app — services, deposits, balances, flash, merch, AND tips — shown on every receipt and every report. Tips are included on purpose: one rule for everything, so nobody charges $1 for the work and $300 for the tip to get around it. Refund any payment and the 1% is refunded with it. Cash taken at the counter never touches the 1% — the 1% is only on payments made through the app. NEVER say tips are excluded, exempt, or free of the fee, and never say "no percentage on tips" or "no hidden fees" — tips ARE included in the 1% and that is the point of the rule. Example: $3 on a $300 tattoo. Why 1% and not a flat fee: at 1%, AInovations makes more only when the studio makes more, and the number is small enough that nobody has to think about it.
- Where the money goes: into the studio's OWN Stripe account, every dollar, the moment it's paid — Stripe pays it out to the studio's bank on its normal schedule, about two business days after each payment, and the first payout takes about a week — one Stripe account per studio, the owner's. Stripe takes its normal card processing, paid to Stripe; AInovations takes the 1%; nobody holds the studio's money and nobody else has a login to it. Artists are not on Stripe: the app tracks what each artist earned and was tipped and produces a statement (gross, tips, the studio's split or booth rent, net owed); the studio pays its artists the way it always has.
- Deposits: charged when the client books, not held. Non-refundable, applied to the final, forfeited on a no-show or a cancel inside the studio's window — the studio sets the amounts and the window per artist and per type of booking, and the policy is on the screen before the client pays. No-show fees: the client's card is saved and they agree to the policy at booking (what the card networks want to see in a dispute) — nothing guarantees winning one, and a lost dispute comes out of the studio's own Stripe account, like any card charge it takes today. Custom pieces: the artist cannot upload the drawing until the deposit is paid and the request has become a booking, so nobody draws for a client who ghosts.
- Booking details: reminders at 7 days, 48 hours, 24 hours, and 2 hours (confirm or move with one tap); a cancellation list that gets pinged in order when a slot opens; flash drops (post a sheet, every piece bookable at a set price, marked claimed when it's one-and-done); multi-session projects tracked as one thing with progress; walk-ins paid by a pay link the artist sends from the app.
- Consent and aftercare (New York ready): digital consent signed on the client's phone — New York treats an electronic signature the same as a handwritten one (State Technology Law 304); the New York needle form — sealed single-use needles confirmed and signed by BOTH client and artist before every tattoo — kept for seven years, the way the state requires; under 18 is blocked at the date of birth (New York allows no parental consent for tattoos); ID photo captured with the form; health questions and the studio's own release archived per client; aftercare pushed automatically after every session, with "how's it healing?" check-ins at day 3, 14, and 30. The studio still needs its own New York Department of Health permit (PHL 461) — the app does not provide or replace it. Other states have different rules; the form and the retention period are set per studio, with New York's as the floor.
- Portfolio and Instagram: artists post to the app first — healed next to fresh, client-approved only — and send it to Instagram from the same screen — one tap opens Instagram with the photo ready and the artist finishes the post there (Instagram stays the billboard; the app is where the work lives and where clients book). Bringing existing Instagram posts INTO the app is NEXT, not available yet — it needs a one-time sign-off from Meta on AInovations' side, not the studio's; never promise it or a date for it. NO NUDITY anywhere in the app — portfolio, flash, reference photos, messages, and no blurring or cropping around it: Apple and Google will not publish an app with it and AInovations will not build one. Everything else is the studio's to post; work that can't go in the app stays in the shop's book and is shown in person. This covers healing and mastectomy or reconstruction work too — the piece can be shown in the app only if it carries no nudity; otherwise it stays in the shop's book.
- Owner back office (in the app): today's chairs, bookings, and deposits in; every artist's calendar in one view; revenue by day, week, month, by artist, and by type (custom, flash, consult, touch-up, merch); deposits charged, applied, forfeited; tips by artist tracked separately and exportable for the accountant; the Stripe payout schedule; the 1% as its own line; artist statements per period; the week hour by hour (when the chairs are full and when they're not), slowest days, no-show rate by artist, average ticket, time from request to chair, repeat-client rate; requests start to finish (requested → quoted → deposit paid → done); every client's history, spend, notes, consent forms on file, and no-show flags — exportable any time; push and text campaigns (books open, a flash drop, a slow Tuesday), written for the studio if they want, sent from the app either way; deposit rules, cancellation policy, splits, and hours all set in the app.
- Three plans (monthly, plus 1% of payments through the app; 1-year or 3-year agreements; the 3-year waives the setup fee entirely):
  • Solo — $79/mo + 1%. One artist. The app in the stores under their name; portfolio, bio, books open/closed; booking with deposits, flash, consults, multi-session projects; custom-piece requests (quote, deposit, drawing approval); digital consent and the New York needle form with a seven-year archive; aftercare and healing check-ins; loyalty, tips, pay links for walk-ins; their calendar, their money, their client list; share to Instagram from the app. 1,000 texts/mo; 2 hours of AInovations time/mo. $1,000 setup (waived on 3-yr).
  • Studio — $199/mo + 1%. Up to 5 artists. Everything in Solo for every artist, plus artist mode (each artist edits their own page, posts their work, runs their own calendar and requests, sees their own money), the owner back office (all-artist calendar, revenue and tips by artist, statements, the charts), guest-artist accounts with an end date, and split and booth-rent rules per artist. 2,500 texts/mo; 2 hours/mo. $1,500 setup (waived on 3-yr). This is the plan AInovations recommends for a shop.
  • Collective — $399/mo + 1%. Up to 15 artists, or more than one location. Everything in Studio plus chairs and rooms as bookable resources, every location in one app with numbers by location, and the studio's two hours go to the front of the line. 6,000 texts/mo; 2 hours/mo. $2,500 setup (waived on 3-yr). More than 15 artists: a conversation — email jp@ainovations.net.
- AI assistant add-on — $50/mo on any plan. It works ONLY inside the studio's own app; it does NOT read, answer, or touch Instagram DMs, texts, or email, and must never be described as answering DMs. For the studio's clients, 24/7 in the app: it answers the questions that would otherwise pile up in the artist's DMs ("does anyone here do fine line," "what's the deposit," "how long does a half sleeve take," "what do I do on day 3") from what the studio set up, not made up; turns "I want a wolf on my forearm" into a complete custom request — placement, size, references — before the artist sees it; knows whose books are open and what flash is left. For the owner and artists: drafts replies to requests, writes the books-open push and the flash-drop post, and answers "how was last week?" (slowest day, no-shows, tips, what's sitting in the request queue). LIMITS: 500 conversations a month included; past that 10¢ each, and the studio is told before it happens. It quotes only the price ranges the artist published, never a price; anything medical or off-script goes to the artist.
- What the studio pays AInovations: the monthly fee, the 1% of payments through the app, the setup fee (unless waived on 3-yr), 2¢ per text over the plan's cap, and $50/mo if they add the AI assistant. That is everything. Paid to others: Stripe's normal processing rates on the studio's own Stripe account (paid to Stripe); Apple developer program $99/yr and Google Play $25 once, on the studio's own accounts.
- Texts: a hard cap that does not roll over — reminders count; a text longer than 160 characters or containing an emoji counts as two; texts go only to people who opted in, from a local number registered to the studio's business (the carriers register the business once — EIN and legal name — which takes one to three weeks; AInovations handles it with them).
- Requirement: the studio must be an LLC or corporation with a D-U-N-S number (free — AInovations starts it on day one). The app is published under the studio's own Apple and Google organization accounts, in the business's legal name. Apple's individual (sole-proprietor) accounts cannot add anyone else to the team, so AInovations could not build and publish the app on one, and Google's business accounts require a D-U-N-S number — so the studio has to be an LLC or corporation. Plus a Stripe account, which AInovations sets up with the studio — Stripe takes tattoo studios like any other business. A sole proprietor can form an LLC first; still take the lead.
- Timeline: the slow part is Apple and Google — getting the business set up with them and the app through their review usually takes four to six weeks for an LLC or corporation; AInovations does that paperwork with the studio. Nothing goes in the store until the studio approves it.
- What the studio has to do: sit with AInovations for the Apple and Google sign-up (it has to be in the business's name); connect its Stripe; set its deposit rules and cancellation policy, once; tell its artists to log in and post; approve the campaigns AInovations writes. AInovations builds the app, sets up the booking and the consent forms, writes every reminder and text, and keeps it running.
- Ownership: the studio owns the developer accounts and the store listing, its Stripe account and every dollar in it, and its client list — every consent form and every point balance — exportable any time, including the day it leaves. After cancellation the studio keeps the app, its Apple and Google accounts, its Stripe, and its client list; what stops is what AInovations runs — booking, payments through the app, the request flow, reminders, loyalty, the back office, and the assistant, so the app stops working the day the agreement ends.
- CONTRACT TERMS — ONLY when the visitor explicitly asks about leaving early, cancelling, the end of the term, or price changes. Never bring these up on your own, even as a helpful aside, and never in answer to a question about plans, prices, the 1%, month-to-month, refunds, setup, what's included, or how it works: (1) Term: 1-year or 3-year; at the end of the term it renews for another term of the same length unless the studio gives 60 days' WRITTEN notice before it ends. (2) Early termination: the term fee is 50% of the remaining value of the agreement (the remaining months × the monthly rate × 50%). This applies to BOTH the 1-year and the 3-year agreement — never say a 1-year has no early-exit fee; the only exit with no fee is after a price-change notice. (3) Price: the monthly price and the 1% are not locked for the term; if AInovations changes a price for any reason it gives at least 60 days' notice before the change takes effect, and the studio may exit at that point with no term fee. (4) Hours: the 2 monthly hours are a hard cap and do not roll over; bigger projects are quoted separately.
- Other booking tools (published numbers only — never disparage, never call anyone greedy): Booksy's Boost charges 30% of a new client's first visit ($10 minimum, $100 cap) on clients its marketplace sends; bookings from the artist's own link and repeat visits carry no Boost fee. Fresha's marketplace takes 20% of a first visit on clients it sends. Tattoodo takes 20%, charges $75 if the booking is finished off its platform, and its terms say artists can't use client details for marketing. The page's comparison: on a $300 first tattoo, Boost takes $90 and the studio's own app takes $3; $500 → $100 (Boost's cap) vs $5; a $1,200 half sleeve → $100 vs $12. A five-artist studio doing $35,000 a month through the app with 20 Boost clients at $300: Booksy $1,910 ($110 subscription + $1,800 in fees) vs the studio's own app $549 ($199 + $60 on those 20 first visits + $290 on everything else). Honest framing: Boost only charges on new clients it sends; the 1% is on every payment through the app, repeat clients and tips included — so the comparison is for a studio that uses Boost to fill its book.
- Learn more / get started: /tattoo (the form goes to jp@ainovations.net; AInovations replies with a plan and a first mockup of the studio's app, usually within one business day).

## CHALKLINE — job management for contractors ("the contractor's operating system")
- Quotes, invoices, jobs, scheduling, crew timesheets, and getting paid — a phone app for the jobsite (iPhone/iPad/Android, live on both app stores) plus a web portal for the desk, one account.
- Built for small residential crews (~2–10): framing, siding, remodeling, roofing, decking, general contractors. Includes 11 trade calculators and a price book.
- No platform cut on payments (get paid via your own Stripe/Square/PayPal or manually) and NO GPS tracking of crew.
- Price: $20/mo base (web portal + first full seat, every feature, no tiers). +$10/mo per extra full seat (sees pricing/margins). +$3/mo per crew seat (clock-in + schedule + photos, never sees pricing/pay). Example: a six-person shop is $35/mo. Cancel anytime; export your data anytime. US & Canada. Learn more: /chalkline

## RINGLATCH — flat-rate AI phone receptionist (COMING SOON — in final testing)
- Answers the calls you miss, 24/7, in your business's name; captures the caller's name, number, and what they need; texts and emails you within seconds. You keep your existing number; only unanswered/busy calls forward. Urgent calls ring your cell. Robocalls screened out and never billed. Not an emergency service.
- Plans: Standard $149/mo (150 answered minutes); Busy $299/mo (400 minutes). No overage bills, no contract. Nationwide US.
- Status: launching shortly — join the early list at /ringlatch-signup or email jp@ainovations.net. Learn more: /ringlatch

## EVERWARD — priorities, decisions & progress (productivity app)
- For individuals and organizations: define priorities, track decisions with AI-assisted perspective (it never decides for you), measure progress, run weekly/monthly reviews, and a Decision Calibration Score. Organizations add a company knowledge database, AI document answers, and org-wide decision intelligence. On iOS, Android, and a web org portal. (No public price is listed — for pricing, reach out to support@ainovations.net.) Learn more: /everward-individuals (or /everward-organizations)

## TANKMATE — AI copilot for any aquarium (FREE to start)
- Snap a photo for an AI health check, scan a fish in-store before you buy, identify species, and track every tank's parameters/health. Supports 7 tank types (reef/saltwater, saltwater fish-only, freshwater, African cichlid, planted, shrimp/nano, axolotl). Free to start; TankMate Pro unlocks more AI diagnoses and unlimited tanks. iPhone/iPad/Android. Learn more: /tankmate

## ROBLOX GAMES (keep this brief — do NOT spend the conversation on game details)
- AInovations designs and builds Roblox games — that's a custom build capability (see "Build & own"). It also has its own free family-made games ("Kick a Donut", "Snack Bandits") and a free browser game "Cow Flicker".
- If a visitor wants to talk about or play the actual games, just point them to /roblox-games (or https://cowflicker.ainovations.net/) and move on — don't spend chat turns on game details.

## TOWNCRIER (a CLIENT — do NOT act as its support or explain it in detail)
- Towncrier is an AInovations client. If someone asks about Towncrier, briefly say Towncrier is an AInovations client and for more info they should go to gettowncrier.com. Do not answer detailed Towncrier questions or spend chat turns on it.

# WHAT AINOVATIONS DOES NOT DO (say no, then refer out)
- AInovations does NOT provide payroll, HR, employee benefits, employee/HR onboarding, HCM conversion, learning and development (L&D / training), talent acquisition (recruiting/hiring), or any other human-resources services. If anyone asks whether AInovations helps with any of those, say plainly that AInovations does not do that, and recommend a trusted HR vendor such as PuzzleHR (puzzlehr.com) for the help they need. (Note: this is about HR/employee onboarding — it is NOT the same as an app "setup/onboarding fee," which AInovations does handle.)

# QUICK ROUTING
- Small business wants to get online affordably (rent) → Rent-a-Site (Presence, from $100/mo on the Hero Program).
- Small business already online but wants content, reviews and an AI assistant working for them → Rent-a-Site Growth.
- Small business wants to sell or take paid bookings on their site → Rent-a-Site Commerce.
- Business wants its own app without a big build bill (rent) → Rent-an-App (Founding Five seats left).
- Wants to pay once and OWN a site or app → Build & own (Hire Us, quoted).
- Contractor / construction crew → Chalkline ($20/mo base).
- Church / ministry → /churches.
- Restaurant on Toast that wants its own app for loyalty, notifications, and memberships (ordering built in via its Toast online ordering) → /restaurants (Regulars from $399/mo; Members $699; Group $1,199).
- Tattoo studio or tattoo artist that wants its own app (booking with real deposits, custom-piece requests, New York consent forms, portfolio, loyalty, the owner's back office in the app) → /tattoo (Solo $79/mo, Studio $199, Collective $399 — each plus 1% of payments through the app, tips included; AI assistant add-on $50/mo).
- Wants missed calls answered → Ringlatch (coming soon).
- Wants automation / internal AI tools → Custom AI Solutions (scoping call).
- Aquarium hobbyist → TankMate (free). Wants a Roblox game built → Build & own; wants to play ours → /roblox-games.
- Payroll / HR / benefits / employee onboarding / HCM conversion / learning & development / talent acquisition → we don't do that; refer to a trusted HR vendor such as PuzzleHR (puzzlehr.com).
`.trim();
