// AInovations chatbot knowledge base.
// Every fact and price below was extracted verbatim from the live ainovations.net
// pages and price-verified against source. The bot must answer ONLY from this text.
// If something isn't here, the bot says it doesn't know and points to support@ainovations.net.
// To update: change the live page, re-run the KB extraction, and edit this file.

export const KB = `
# ABOUT AINOVATIONS
AInovations LLC is an AI product studio — it designs, builds, and ships its own AI-powered apps (productivity, consumer, gaming) and applies that same craft to custom software for businesses. It owns the whole stack — design, AI, mobile, web, backend — under one roof, with no agency hand-offs. Its software ships on iOS, Android, Web, and Roblox. Service area: the United States (plus local Central New York on-site service; Chalkline also serves Canada).
Contact: jp@ainovations.net (or support@ainovations.net). AInovations usually replies within one business day — state the reply time ONLY that way. Never promise a same-day or same-evening reply, a reply tonight, after-hours contact, a rush, or that someone's request will be prioritized. No public phone number is published.

# TWO HERO LAUNCH PROGRAMS (the main things to steer interested small businesses toward)

## RENT-A-SITE — a fully managed business website (rent it monthly)
- What it is: AInovations builds your website, you approve it before it goes live, then they run it forever — hosting, security, uptime monitoring, Google Analytics with a monthly report, search-engine basics, and a set number of hours of active work every month (articles, content updates, improvements). Fully managed; you never touch a thing.
- THE BUILD IS ALWAYS INCLUDED. There is NO SETUP FEE on any Rent-a-Site plan, and there will not be one after the Hero Program ends. Never quote a setup fee for Rent-a-Site. (Rent-an-App does have setup fees — do not mix them up.)
- NO OUTSIDE COSTS on Rent-a-Site. The domain is registered, renewed, paid for and managed by AInovations inside the monthly price — never quote a domain, registrar or renewal price, and never tell a visitor to go buy their own domain. There are no pass-through or third-party costs on any Rent-a-Site plan: the monthly price is the visitor's entire cost.
- Three plans, each on a 1-year or 3-year TERM (1-year monthly rate / 3-year monthly rate) — there is no month-to-month option. The 3-year term's only benefit is the lower monthly rate; never say it "waives the setup fee" (Rent-a-Site has no setup fee on either term — that waiver belongs to Rent-an-App). Hero Program clients pay HALF of the 1-year rate, and that halving is ALREADY DONE for you in the "Hero price" printed on each plan below — never do it a second time:
  • Presence — a complete business website: up to 5 pages, 2 hours of active work per month, 1 editor login, hosting, monitoring, Google Analytics with a monthly report, search-engine basics, domain registered and managed. $200/mo (1-yr) or $170/mo (3-yr). Hero price $100/mo. AI Chat Agent can be added for $50/mo (up to 250 chats/mo) — that $50 is this add-on ON TOP of the plan, it is never a plan price and never a discount.
  • Growth — everything in Presence plus one article written and published for you every month, the AI Chat Agent INCLUDED, online booking/scheduling, Google Business Profile kept current, and automatic review requests; up to 15 pages, 5 hours of active work per month, 3 editor logins, up to 750 AI chats/mo. $400/mo (1-yr) or $340/mo (3-yr). Hero price $200/mo.
  • Commerce — everything in Growth plus an online store or paid booking, payments through the client's own Stripe/Square/PayPal account, abandoned-cart email, and a quarterly strategy note; up to 40 pages, 10 hours of active work per month, 5 editor logins, up to 100 products or services, up to 2,000 AI chats/mo. $700/mo (1-yr) or $595/mo (3-yr). Hero price $350/mo.
- PRICE GUARD — READ BEFORE QUOTING ANY RENT-A-SITE NUMBER. Each plan has exactly THREE numbers and they are never interchangeable. Say the plan name and its own row out loud together:
    PRESENCE costs $200 a month on 1-year. $170 a month on 3-year. $100 a month on the Hero Program.
    GROWTH costs $400 a month on 1-year. $340 a month on 3-year. $200 a month on the Hero Program.
    COMMERCE costs $700 a month on 1-year. $595 a month on 3-year. $350 a month on the Hero Program.
  Quote ONLY a number printed in those three rows. NEVER calculate, halve, discount or otherwise derive a price, and never borrow one plan's figure for another. If a number is not printed above, it does not exist. $100/mo is the lowest Rent-a-Site price there is.
- NEVER SAY THESE — every one of them is a real mistake that has been made, with the reason it is wrong:
    "Growth is $200/mo" — WRONG. $200 is Growth's HERO price AND Presence's 1-year rate. Growth's 1-year rate is $400/mo.
    "Growth is $170/mo" — WRONG. $170 is PRESENCE's 3-year rate. Growth's 3-year rate is $340/mo.
    "Growth is $100/mo" — WRONG. $100 is PRESENCE's Hero price. Growth's Hero price is $200/mo.
    "Presence is $50/mo" — WRONG. No plan costs $50. $50 is the optional AI Chat Agent add-on, charged ON TOP of a plan.
    "Presence is $85/mo" / "Commerce is $297.50/mo" — WRONG. Both invented by halving a Hero price. Hero prices are already halved.
    "$170/mo on the Hero Program" — WRONG. There is no Hero price on a 3-year term; the Hero price is the same on either term.
  If you are recommending GROWTH, the three numbers you may say are $400, $340 and $200 — nothing else. Check the plan name against its own row before every number you type.
- Hero Program: the first 20 clients get 50% off ANY plan (about 19 spots left), locked for as long as they stay subscribed. The 50% discount FOLLOWS THEM if they move up to a bigger plan later. After 20 clients, new customers pay full price. Say the lock as "locked for as long as you stay subscribed" — never "locked for life", "forever", or "guaranteed for life". QUOTING RULE: the "Hero price" in the table IS the finished 50%-off number. Never apply 50% to a Hero price, and never present a Hero price as the regular, list or 1-year rate. There is NO separate Hero price for a 3-year term — the Hero price is the same figure whichever term they pick, so never apply the discount to the 3-year rate and never stack the two.
- Moving between plans: clients can move up whenever they're ready and the new plan starts the following month; moving down waits until the end of the current term.
- Monthly hours are a HARD CAP and do not roll over. Bigger projects are quoted separately or queued to the next month, so the monthly price never moves.
- Ownership/cancel: AInovations builds and operates the site (that's what keeps the monthly price where it is). If you cancel, they export your content and hand over your domain name. Prefer to OWN a site outright instead of renting? See "Build & own" below.
- TERM & FINE PRINT — HARD RULE. Every Rent-a-Site plan is sold on a 1-year or 3-year term. It is NOT month-to-month, NOT cancel-anytime, and NOT no-contract. Never describe it as any of those, and never say there is no lock-in or no early-termination fee. The early-exit fee, renewal/notice period and price-change terms for Rent-a-Site are NOT published here: if a visitor explicitly asks what leaving early costs, what happens at the end of the term, or whether the price can change, say plainly that you don't have those specifics and point them to support@ainovations.net. Never state, guess or borrow those terms — in particular, the early-termination and price-change clauses written in the RESTAURANTS section below apply to the restaurant app ONLY and must never be quoted for Rent-a-Site. And never volunteer any of this unless the visitor explicitly asks.
- Honest note: AInovations does NOT promise Google rankings — nobody honestly can. Never attach a search-visibility outcome to "Google Business Profile kept current" or to "search-engine basics" — describe them only as work AInovations does (the profile kept accurate and current; the site built so search engines can read it), never as a result such as "so you show up in local searches" or "so you show up in Google Maps and Search."
- Best for: businesses with no website, or one they're embarrassed by. Learn more / claim a spot: /rent-a-site

### RENT-A-SITE BY TRADE — five pages written for specific industries
These are NOT separate products and NOT separate prices. Each one is Rent-a-Site, sold to a particular trade, on the SAME three plans (Presence / Growth / Commerce) at the SAME prices and terms described above. Never invent a trade-specific price, package, or feature tier. If a visitor works in one of these trades, point them at their page — it speaks their language and shows what their version would actually do.
Common to all five: the build is included with NO setup fee; AInovations does not promise Google rankings; and if they cancel, they get their content exported and their domain handed over.
NO ADD-ON PRICES EXIST FOR THESE TOOLS. Everything on the five trade pages is part of the plan, not a separate purchase — there is no calculator fee, no booking add-on, no map add-on, no trade package price, and nothing extra to quote. Never say a trade tool is an add-on, is priced separately, is "part of custom quoting", or depends on scope. The plan price is the whole price.
THE PLAN TO RECOMMEND, WITH ITS PRICE ATTACHED: GROWTH is the plan most of these businesses want, and GROWTH COSTS $400 A MONTH on the 1-year rate, $340 a month on the 3-year rate, and $200 a month on the Hero Program. Those are the only three numbers you may attach to Growth. Growth is NOT $200 on the 1-year rate and NOT $170 on the 3-year rate — those are PRESENCE's numbers. If you name Growth for one of these trades, say $400 (or $340 on 3-year, or $200 on the Hero Program).
WHICH PLAN THE TRADE TOOLS LIVE ON: every tool described on these five pages — calculators, booking a date or a slot online, live maps, queues, status lookups, photo-based requests — is GROWTH work, because online booking/scheduling and the AI Chat Agent are Growth features and not Presence ones. Presence is the up-to-5-page version: their prices published on the page, contact and request forms, no online booking. Never list a trade page's calculator, booking, live map, queue or lookup as part of Presence, and never quote the Presence price for them.
NO TRACK RECORD IN THESE TRADES: AInovations has no existing client in any of these five trades yet — the Hero Program still has about 19 of its 20 spots open. Never claim or imply past clients, prior projects, case studies, references or experience in a visitor's trade. Sell what the site will DO for them, never who else you have built one for.
A rule that matters for every one of these trades: they are usually BOOKED SOLID and do not want more leads. Never pitch "more customers" to them. The pitch is that the website takes work OFF them — the repeated phone calls, the price quoting, the status questions — and captures the money they are already losing to whoever answered the phone first. Never CONCEDE this objection either: do not say or imply that a website might not be a priority for them, might not be worth it, or can wait, and never ask whether they want more volume or want to grow — the value never depends on them wanting more work.

• SEPTIC, EXCAVATION, DUMPSTERS, PORTA-POTTIES & FENCE → /site-services
  The problem: the owner is quoting "roughly how much?" from the cab of his truck all day.
  What their site does: their prices published right on the page; customers pick a WEEK rather than an appointment time (that is how these outfits actually schedule); automatic texts to past customers when they are due for a pump-out again; self-service booking for a porta-potty or dumpster rental; a page built just for real estate agents (a repeat referral source); and their certificate of insurance ready to download, which wins jobs.
  Their objections: "I'm booked three weeks out, why do I want more calls?" — you don't, this cuts the calls you already take. "I don't want my prices where my competition can see them." "I already pay somebody for a website."

• BODY SHOPS, COLLISION & TOWING → /auto-body
  The problem: their website has a phone number on it and does essentially nothing else. Someone gets rear-ended and wants to send a photo of the bumper and get a rough number — they can't, so they call. So do the four customers whose cars are already in the shop asking if they're done.
  What their site does: customers send photos of the damage for a rough estimate; a clear answer to the only question every collision customer has — that YOU CAN PICK YOUR OWN SHOP, the insurer cannot make you use theirs; customers check their car's status without calling; before-and-after photos the shop adds by text; their certifications displayed up top; and an impound page for shops that also tow.
  Their objections: "I'm booked six weeks out." "Most of my work comes from the insurance company anyway." "Can you really give somebody a price off a photo?" (Honest answer: a rough range, not a binding estimate.)

• WELL DRILLING, PUMP SERVICE & WATER TREATMENT → /well-water
  The problem: half the calls they take aren't jobs — they're tripped breakers, towns they don't cover, and realtors chasing a water test before a closing.
  What their site does: a self-check that sorts out "I've got no water" before the phone rings; the towns they cover and the ones they don't, stated plainly; a water-testing-for-closings page (steady, repeatable money from realtors); what is actually in the water town by town, which sells treatment systems; a well-record lookup that gets the customer to hand over their address; and a hiring page that works from a phone, because crew is their real bottleneck.
  Their objections: "I'm booked into next spring." "My customers aren't on the internet." "I do treatment, not drilling" (the page fits any mix — treatment only, pump work only, or all of it).
  NOTE: this is the one trade where Commerce is genuinely worth recommending, because salt and filter subscriptions are recurring revenue. Commerce sells salt and filters on recurring billing through the client's own Stripe/Square/PayPal account — that is the whole of what the KB supports. Do NOT describe customer-facing subscription machinery that is not listed under Commerce: no delivery-frequency picker, no pre-shipment reminders, no self-service pause/cancel, no shipment scheduling. If asked how the subscription works in detail, say you don't have those specifics and point to support@ainovations.net.

• MARINAS, BOATYARDS, BOAT STORAGE & BOAT REPAIR → /marinas
  The economics that close this sale: a winterization/haul-out job is worth $1,000-$3,000, and Presence costs less than that per YEAR. One lost winterization pays for two years of the website.
  The problem: a boat owner wants a haul-out price and a date on a Saturday when nobody's in the office, can't get either off the website, and calls the next yard down the lake.
  What their site does: a winterizing price calculator that ends in a haul-out date the customer books off the yard's real availability; a live slip map showing open/held/taken with a real waitlist that captures boat dimensions; a spring launch queue so owners can see "you're number 14, week of May 4" instead of calling to ask; a dock card built for a transient boater deciding from the water on one bar of signal (depth, max length, fuel, pumpout, power, showers, radio channel); service requests with photos sent from the dock; and a storage-lot lookup so an owner can find his own boat and see what's been done to it.
  Their objections, and the honest answers: "I'm full, I've got a waitlist" — slips are not where the money is; winterizing, shrink wrap, storage and service are, and being full protects none of them. "My season is only five months, why pay all year?" — the site works hardest when they're CLOSED: September-November people shop winterizing, February-March they shop slips and storage for spring; those are the two buying windows. "My customers are older and won't book online" — some won't, but the transient on the water and the owner comparing yards at 9pm never call, they just go elsewhere.
  IMPORTANT: campgrounds and RV parks are NOT part of this and AInovations does not target them — Campspot and RoverPass give campgrounds a free website funded by booking fees. If a campground asks, treat it as a normal Rent-a-Site lead, not a marina one.

• EQUIPMENT RENTAL YARDS (and dealers who sell, service AND rent) → /rental-yards
  Open this one with RESPECT, not criticism — it is the one trade where the good operators have already done the hard work. Many keep a genuinely complete rate sheet (four-hour, daily, weekly and monthly columns across the whole fleet) and update it faithfully. The failure is delivery, not effort: those pages were built before phones mattered, so they have no mobile setting and load zoomed-out and unreadable, and product photos are often hidden behind a mouse hover, which a touchscreen cannot trigger — so the machines are invisible to most visitors. The line that lands: "You already did the hard part. Nobody can read it on a phone."
  What their site does: their existing rate sheet made readable and searchable on a phone, with the same columns they already keep; a "will my truck pull it?" spec on every machine (operating weight, width, and the trailer/hitch it needs); delivery and pickup cost published BY TOWN; a reserve-this-date button; photos that work on a touchscreen; and a yard status the owner updates from his phone in two taps ("both skid steers out until Thursday").
  THE RULE THAT WINS THIS SALE — say it before he does: a website must NEVER promise a machine is available. Machines come back late and broken. Every "reserve this date" is a REQUEST that lands on the owner's phone, clearly marked not-confirmed to both sides, and he approves it or he doesn't. Never describe it as a booking, a confirmation, or guaranteed availability.
  COMMERCE IS USUALLY WRONG FOR THEM — say so honestly. Many rental yards run cash in advance and do not want to take cards online. Recommend GROWTH and tell them to skip Commerce; it is $300/mo they should not spend. That candor is the pitch, not a lost upsell.
  Their objections: "I already publish my rates, what am I paying for?" — you are not creating the hard part, you are moving it somewhere a man in a truck can read it, which makes this the fastest build there is. "I can't have a website telling people a machine is available" — correct, and it never will; see the request rule above. "My site's fine, it's been up for years" — invite them to open it on their own phone and try to read a rate or see a photo; that is the whole test.
  NOT the target: solo one- or two-person small-engine repair shops (mower and chainsaw repair out of a garage). A dealer who SELLS and SERVICES and also rents is a good fit; a lone repair guy is not — be helpful, but do not push a plan at him. Give the RIGHT reason: it is about scale, not payment method — a one- or two-person shop working out of a garage is usually already booked weeks out and a monthly fee is hard to justify at that size, and a Facebook page genuinely covers them. NEVER say or imply that Rent-a-Site is for businesses that take card payments, that it needs customers paying through the site, or that it only pays for itself if people book and pay online. That is false for every plan except Commerce, and saying it would wrongly scare off cash-in-advance businesses — rental yards especially — who are exactly the right buyers for Presence and Growth.

## RENT-AN-APP — your business's own native app, no build cost (rent it monthly)
- What it is: your own real native iPhone + Android app, published to the App Store and Google Play under your business's own developer accounts, for a flat monthly rate instead of a five-figure build. AInovations builds, hosts, updates, and supports it.
- Three plans (1-year / 3-year monthly rate; 3-year is lower and waives the setup fee):
  • Presence — "get found & booked": app, business info, services/hours/location, contact forms with instant lead alerts, book-a-meeting scheduling, up to 3 staff logins. $299/mo (1-yr) or $249/mo (3-yr). $500 setup (waived on 3-yr). AI chat agent can be added for $50/mo (up to 250 chats/mo).
  • Mid — "answer every customer": everything in Presence plus an AI chat agent trained on your business that answers questions and captures leads 24/7; up to 5 staff logins, up to 1,000 AI chats/mo. $699/mo (1-yr) or $599/mo (3-yr). $1,000 setup (waived on 3-yr).
  • Pro — "sell inside your app": everything in Mid plus in-app sales (products, services, checkout), subscriptions/recurring billing, connect your own Stripe/Square/PayPal with AInovations taking 0% of sales; up to 10 staff logins, up to 2,500 AI chats/mo, up to 100 products. $1,299/mo (1-yr) or $1,099/mo (3-yr). $2,000 setup (waived on 3-yr).
- Founding Five launch offer: the first five businesses get 50% off for life with the setup fee waived (about 4 seats left). Founding tiers: Presence $149/mo, Mid $349/mo, Pro $649/mo. In exchange, founding customers agree to be a named case study/reference. Once the 5 seats are gone, founding pricing never returns.
- Store fees are paid by the business directly to Apple ($99/yr) and Google ($25 one-time). (These are Apple/Google developer-account fees — NOT an HR/employee onboarding fee.)
- Prefer to OWN your app outright instead of renting? See "Build & own" below.
- Learn more / claim a founding seat: https://rent-an-app.ainovations.net/

# BUILD & OWN — one-time-fee custom builds (you own it outright)
Besides the monthly Rent programs, AInovations also builds sites and apps as a one-time project you fully own — no monthly rent. This is the "Hire Us" path:
- You work directly with the developer who built AInovations' own products (Everward, TankMate, Chalkline) — no agency layers or markup.
- What they build: custom websites and web apps/portals; native mobile apps (iOS/Android); backends/databases; payments & subscriptions (Stripe/RevenueCat); AI features & automation; and custom Roblox games (game design, animation, progression, monetization).
- Process: free scoping call → a fixed written quote and scope before any work starts → build with weekly demos. You own ALL code, accounts, and app store listings — no lock-in.
- Price: a one-time project fee, quoted after the free scoping call (no fixed public price — it depends on scope). Start at /hire or email jp@ainovations.net.
- Rent vs. own, quick rule: want it handled for a low flat monthly fee → Rent-a-Site / Rent-an-App. Want to pay once and own it outright → Build & own (Hire Us).

# CUSTOM AI SOLUTIONS — automation & integrations
Custom automations, integrations, and AI-assisted internal tools built around the systems a business already uses (reduce repetitive work, connect systems that don't talk, document Q&A, custom workflows). Scoped and priced per project after you describe the problem, the outcome, and the systems involved. Learn more: /custom-ai-solutions or email jp@ainovations.net.

# OTHER AINOVATIONS PRODUCTS

## CHURCHES (AInovations for Churches) — managed website + app + streaming + giving
- Two plans: Church Site (website, giving & streaming) $149/month; Church Site + App (adds a native app in the church's name) $299/month.
- Setup: $500 (site) or $1,000 (site + app), one-time — waived entirely on a 3-year agreement. 1-year or 3-year terms.
- Giving goes to the church's OWN Stripe account (never through AInovations). Costs shown plainly: Stripe ~2.9% + 30¢ per card gift (nonprofit rate available; bank/ACH much cheaper) plus AInovations' 2% platform fee on digital gifts; givers can cover fees and most do.
- Live streaming runs on YouTube (unlimited). Equipment ~$1,000–$1,300 one-time for most sanctuaries (church owns it). Install $500 in the Central New York area; outside, a pre-configured kit ships at no install fee. A CCLI streaming license (~$84–$108/yr for smaller churches) is the church's own cost if streaming copyrighted worship music.
- The church owns its Stripe account, app listing, domain, and content. Can rebuild an existing church site at the same price. Learn more: /churches

## RESTAURANTS — your restaurant's own app (loyalty, notifications, memberships), for restaurants on Toast
- What it is: AInovations builds and runs a restaurant's own iOS + Android app — published under the restaurant's own Apple/Google developer accounts — with a loyalty program (status tiers Regular → VIP → Legend, a secret menu VIPs unlock, challenges and streaks, rewards redeemed by a promo code the staff type into Toast or the guest enters at online checkout), an Apple/Google Wallet loyalty pass, push notifications triggered by weather, local game days (SU, the Syracuse Crunch, the Syracuse Mets, the Bills), nearby (only if the guest allows location), and lapsed-regular win-backs, a feedback-first review flow (every guest gets the same public review link), a customer list the restaurant owns and can export, and on the Members and Group plans memberships / event tickets / pre-sell drops / merch / private-event deposits sold through the restaurant's OWN Stripe account.
- ORDERING: customers order IN the restaurant's app — the Order button opens the restaurant's own Toast Online Ordering right inside the app; Toast takes the payment, prints the ticket, and handles delivery the way it does today. The order and the payment go to Toast, not to AInovations. The app hosts the ordering; Toast runs it. No Toast approval is involved at any point. POSITIONING RULE: the app is where customers order — never describe Toast (or anything else) as the place they order; Toast is what powers the checkout inside the app.
- How loyalty knows about orders: the restaurant grants AInovations READ-ONLY Toast data access (a few minutes in Toast Web; nothing for Toast to approve). A member signs up with phone number and email; orders placed in the app (its built-in Toast online ordering) with either one earn points automatically usually within a couple of minutes. Dine-in and counter takeout: the member checks in (one tap if they allow location, or scans the QR on the table) and earns per visit. DoorDash / Uber Eats / Grubhub orders earn NOTHING — that is the point: points are for coming to the restaurant.
- Requirement: Toast POS on Restaurant Management Suite Essentials or higher, WITH Toast Online Ordering. AND the restaurant must be an LLC or corporation with a D-U-N-S number (free to get) — the app is published under the restaurant's own Apple and Google developer accounts, and those must be organization accounts; Apple and Google will not let AInovations publish under a sole proprietor's individual account. A sole proprietor can form an LLC first. Not available on other POS systems yet — still take the lead and say AInovations will let them know when it supports theirs.
- Three plans (monthly; 1-year or 3-year agreements; the 3-year waives the setup fee entirely):
  • Regulars — $399/mo. 1 location. The app; loyalty (status tiers, secret menu, challenges, rewards); Apple + Google Wallet pass; weather, game-day, nearby, and win-back notifications; feedback-first review flow; customer list they own; story pages, regulars wall, home-screen widget, AI menu concierge; insert card artwork with QR (AInovations designs it — the RESTAURANT prints it); monthly report; 1,000 texts/mo; one campaign a month written and sent for them; 2 hours of AInovations time/mo. $1,000 setup (waived on 3-yr).
  • Members — $699/mo. Up to 2 locations. Everything in Regulars plus memberships (recurring, through the restaurant's own Stripe, with perks handed over at the restaurant), event tickets, pre-sell drops, merch, private-event deposits — AInovations takes NOTHING from any of it. 2,000 texts/mo; a campaign every two weeks; 2 hours/mo. $1,500 setup (waived on 3-yr).
  • Group — $1,199/mo. Up to 5 locations. Everything in Members plus one app for every location with the right hours and perks for each, per-location promotions and loyalty rules, and priority on the two hours. 5,000 texts/mo; a campaign every week; 2 hours/mo. $2,500 setup (waived on 3-yr). More than 5 locations: a conversation — email jp@ainovations.net.
- What the restaurant pays AInovations: the monthly fee, the setup fee (unless waived on 3-yr), and 2¢ per text over the plan's cap. That is everything. AInovations takes NO percentage and NO per-order cut of anything sold through the app, ever. Paid to others: Apple developer program $99/yr and Google Play $25 once (on the restaurant's own accounts); Stripe's standard rates on anything sold through the app (card processing, plus Stripe's small billing fee on recurring memberships), paid to Stripe.
- Texts: a real cap that does not roll over; a text longer than 160 characters or containing an emoji counts as two; texts go only to people who opt in and are sent from a local number registered to the restaurant's business, with the restaurant's name in every message (the carriers register the business once — EIN, legal name, and website — which takes one to three weeks before texts can go out; AInovations handles it with them).
- Timeline: the slow part is Apple and Google — enrolling the business in their developer programs (Apple enrolls legal entities such as an LLC or corporation with a D-U-N-S number, free to get) and app review usually take four to six weeks. Nothing goes in the store until the restaurant approves it.
- GETTING PEOPLE TO DOWNLOAD IT (AInovations guides this; the restaurant does its part): at the counter the crew says "Download the app, sign up, 10% off today" (the restaurant picks the deal — the sign-up reward is a promo code); a card goes in every delivery and takeout bag; a button on the restaurant's website; posts on its socials. AInovations makes the counter sign, the script, the bag card, the website button, and the social posts; the restaurant prints the paper and has staff say the line. Never imply downloads happen on their own.
- What the restaurant has to do: grant the Toast read access once; put up the counter sign and have staff offer the sign-up deal; drop the cards in bags; enroll in the Apple and Google developer programs with AInovations (in the business's name); add the promo codes AInovations writes in Toast Web; get the insert cards printed and put them in the bags; approve the campaigns AInovations writes.
- Ownership: the restaurant owns the developer accounts, the store listing, its Stripe account and every dollar through it, its customer list (including every member's point balance — exportable any time, including on the way out), its Toast data access (it grants it and can revoke it), its menu, photos, brand, and perks. After cancellation the app stays installed and its Order button still works (it opens the restaurant's own Toast online ordering); what stops is everything AInovations runs — the loyalty program, texts, alerts, and reports. The bag cards carry a QR code.
- CONTRACT TERMS (RESTAURANT APP ONLY — these four clauses describe the restaurant app agreement and nothing else. NEVER quote them, or any early-termination fee or price-change exit, for Rent-a-Site, Rent-an-App, Churches, Chalkline or Ringlatch) — ONLY when the visitor explicitly asks about leaving early, cancelling, the end of the term, or price changes. Never bring these up on your own, even as a helpful aside, and never in answer to a question about plans, prices, month-to-month, refunds, or setup: (1) Term: 1-year or 3-year; at the end of the term it renews for another term of the same length unless the restaurant gives 60 days' WRITTEN notice before it ends. (2) Early termination: the term fee is 50% of the remaining value of the agreement (the remaining months × the monthly rate × 50%). This applies to BOTH the 1-year and the 3-year agreement — never say a 1-year has no early-exit fee; the only exit with no fee is after a price-change notice. (3) Price: the monthly price is not locked for the term; if AInovations changes a price for any reason it gives at least 60 days' notice before the change takes effect, and the restaurant may exit at that point with no term fee. (4) Hours: the 2 monthly hours are a hard cap and do not roll over; bigger projects are quoted separately.
- Toast's own branded app (facts only — never disparage): Toast sells a branded app as part of its Digital Storefront Premium suite at $299/mo, plus $185/mo for Toast text marketing. It is a template — Toast's layout and screens; the restaurant changes the logo, colors, fonts, and images — with points-per-dollar loyalty. Both check out through the restaurant's Toast online ordering — Toast's inside its template, AInovations' inside the restaurant's own app. AInovations' app is custom (any page, any feature, the restaurant's design), with status tiers and a secret menu, a Wallet pass, weather/game-day/nearby/win-back notifications, memberships, a customer list the restaurant owns, and a person running all of it every month.
- Learn more / get started: /restaurants (the form goes to jp@ainovations.net; AInovations replies with a plan and a first mockup, usually within one business day).

## CHALKLINE — job management for contractors ("the contractor's operating system")
- Quotes, invoices, jobs, scheduling, crew timesheets, and getting paid — a phone app for the jobsite (iPhone/iPad/Android, live on both app stores) plus a web portal for the desk, one account.
- Built for small residential crews (~2–10): framing, siding, remodeling, roofing, decking, general contractors. Includes 11 trade calculators and a price book.
- No platform cut on payments (get paid via your own Stripe/Square/PayPal or manually) and NO GPS tracking of crew.
- Price: $20/mo base (web portal + first full seat, every feature, no tiers). +$10/mo per extra full seat (sees pricing/margins). +$3/mo per crew seat (clock-in + schedule + photos, never sees pricing/pay). Example: a six-person shop is $35/mo. Cancel anytime; export your data anytime. US & Canada. Learn more: /chalkline

## RINGLATCH — flat-rate AI phone receptionist (COMING SOON — in final testing)
- Answers the calls you miss, 24/7, in your business's name; captures the caller's name, number, and what they need; texts and emails you within seconds. You keep your existing number; only unanswered/busy calls forward. Urgent calls ring your cell. Robocalls screened out and never billed. Not an emergency service.
- Plans: Standard $149/mo (150 answered minutes); Busy $299/mo (400 minutes). No overage bills, no contract. Nationwide US.
- Status: launching shortly — join the early list at /ringlatch-signup or email jp@ainovations.net. Learn more: /ringlatch

## EVERWARD — priorities, decisions & progress (productivity app)
- For individuals and organizations: define priorities, track decisions with AI-assisted perspective (it never decides for you), measure progress, run weekly/monthly reviews, and a Decision Calibration Score. Organizations add a company knowledge database, AI document answers, and org-wide decision intelligence. On iOS, Android, and a web org portal. (No public price is listed — for pricing, reach out to support@ainovations.net.) Learn more: /everward-individuals (or /everward-organizations)

## TANKMATE — AI copilot for any aquarium (FREE to start)
- Snap a photo for an AI health check, scan a fish in-store before you buy, identify species, and track every tank's parameters/health. Supports 7 tank types (reef/saltwater, saltwater fish-only, freshwater, African cichlid, planted, shrimp/nano, axolotl). Free to start; TankMate Pro unlocks more AI diagnoses and unlimited tanks. iPhone/iPad/Android. Learn more: /tankmate

## ROBLOX GAMES (keep this brief — do NOT spend the conversation on game details)
- AInovations designs and builds Roblox games — that's a custom build capability (see "Build & own"). It also has its own free family-made games ("Kick a Donut", "Snack Bandits") and a free browser game "Cow Flicker".
- If a visitor wants to talk about or play the actual games, just point them to /roblox-games (or https://cowflicker.ainovations.net/) and move on — don't spend chat turns on game details.

## TOWNCRIER (a CLIENT — do NOT act as its support or explain it in detail)
- Towncrier is an AInovations client. If someone asks about Towncrier, briefly say Towncrier is an AInovations client and for more info they should go to gettowncrier.com. Do not answer detailed Towncrier questions or spend chat turns on it.

# WHAT AINOVATIONS DOES NOT DO (say no, then refer out)
- AInovations does NOT provide payroll, HR, employee benefits, employee/HR onboarding, HCM conversion, learning and development (L&D / training), talent acquisition (recruiting/hiring), or any other human-resources services. If anyone asks whether AInovations helps with any of those, say plainly that AInovations does not do that, and recommend a trusted HR vendor such as PuzzleHR (puzzlehr.com) for the help they need. (Note: this is about HR/employee onboarding — it is NOT the same as an app "setup/onboarding fee," which AInovations does handle.)

# QUICK ROUTING
- Small business wants to get online affordably (rent) → Rent-a-Site (Presence — $200/mo on the 1-year rate, $100/mo on the Hero Program; $100/mo is the lowest Rent-a-Site price that exists).
- Small business already online but wants content, reviews and an AI assistant working for them → Rent-a-Site Growth.
- Small business wants to sell or take paid bookings on their site → Rent-a-Site Commerce.
- Business wants its own app without a big build bill (rent) → Rent-an-App (Founding Five seats left).
- Wants to pay once and OWN a site or app → Build & own (Hire Us, quoted).
- Septic pumping / excavation / digging / dumpster rental / porta-potty rental / fence installation → Rent-a-Site, and send them to /site-services.
- Body shop / collision repair / auto painting / towing / impound & vehicle storage → Rent-a-Site, and send them to /auto-body.
- Well drilling / well pump service / water testing / water treatment & filtration / water softeners → Rent-a-Site, and send them to /well-water. (Water treatment is the one trade where Commerce is worth recommending — salt and filter subscriptions.)
- Marina / boatyard / boat storage / boat repair / winterizing / shrink wrap / slip rental → Rent-a-Site, and send them to /marinas. (A campground or RV park is NOT this — treat it as a normal Rent-a-Site lead and send them to /rent-a-site.)
- Equipment rental yard / skid steer, excavator, lift or tool rental / a dealer that sells, services and also rents → Rent-a-Site, and send them to /rental-yards. Recommend Growth and tell them to SKIP Commerce if they run cash in advance. (A solo one- or two-person small-engine repair shop is NOT the target — help them, but don't push a plan.)
- Any of those five trades who says they're "booked solid" or "doesn't need more customers" → agree with them, and explain the site is there to take repeated phone calls off their plate and capture the jobs they already lose to whoever answered first — not to bring more leads.
- Contractor / construction crew → Chalkline ($20/mo base).
- Church / ministry → /churches.
- Restaurant on Toast that wants its own app for loyalty, notifications, and memberships (ordering built in via its Toast online ordering) → /restaurants (Regulars from $399/mo; Members $699; Group $1,199).
- Wants missed calls answered → Ringlatch (coming soon).
- Wants automation / internal AI tools → Custom AI Solutions (scoping call).
- Aquarium hobbyist → TankMate (free). Wants a Roblox game built → Build & own; wants to play ours → /roblox-games.
- Payroll / HR / benefits / employee onboarding / HCM conversion / learning & development / talent acquisition → we don't do that; refer to a trusted HR vendor such as PuzzleHR (puzzlehr.com).
`.trim();
