"""Build js/ow-secrets.js: every overworld entrance, how it opens, what is in it.

Position + method (open / bomb / burn / push / recorder) come from the coloured
marker boxes on the labelled Quest-1 overworld map (nesmaps.com), cross-checked
against the cave mouths already present in the terrain dump.

Contents come from template-matching that map's own legend icons against the
map, then attaching each icon to the entrance nearest to it (the map draws an
item's icon just above its cave, which sometimes spills into the screen above).

Run:  SCRATCH=<dir with markers.json + item_hits.json> python3 extract-secrets.py
"""
import json, re, os
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
SC   = os.environ.get('SCRATCH', '.')

markers = json.load(open(os.path.join(SC, 'markers.json')))
hits    = json.load(open(os.path.join(SC, 'item_hits.json')))

# ---- open cave mouths straight out of the terrain data ----
src  = open(os.path.join(ROOT, 'js', 'ow-data.js')).read()
defs = json.loads(re.search(r'defs:\s*(\{.*?\}),\s*\n\s*rows:', src, re.S).group(1))
rows = re.findall(r'"([^"\n]{256})"', src)
CAVE = 14
opens = [(sc, sr, tx, ty)
         for sr in range(8) for sc in range(16) for ty in range(11) for tx in range(16)
         if defs[rows[sr * 11 + ty][sc * 16 + tx]][0] == CAVE]

DUNGEON = {'7,3':1, '12,3':2, '4,7':3, '5,4':4, '11,0':5,
           '2,2':6, '2,4':7, '13,6':8, '5,0':9}

# icon on the map -> what that cave holds. First rule to claim an entrance wins.
ICON_ITEM = [('MAGICAL_SWORD','swordMagic'), ('WHITE_SWORD','swordWhite'),
             ('SWORD','swordWood'), ('LETTER','letter'),
             ('POWER_BRACELET','takeOne'), ('HEART_CONTAINER','heart'),
             ('BLUE_RING','shopRing'), ('LIFE_POTION','potionShop'),
             ('FOOD','shopFood')]

# ---- every entrance, keyed "col,row:tx,ty" ----
caves = {}
for sc, sr, tx, ty in opens:
    caves['%d,%d:%d,%d' % (sc, sr, tx, ty)] = {'sc':sc,'sr':sr,'tx':tx,'ty':ty,'how':'open'}
for m in markers:
    caves['%d,%d:%d,%d' % (m['sc'], m['sr'], m['tx'], m['ty'])] = \
        {'sc':m['sc'],'sr':m['sr'],'tx':m['tx'],'ty':m['ty'],'how':m['how']}

# ---- pull the nine level mouths out of the cave set ----
LEVELTILE = {'7,3':(7,4), '12,3':(7,4), '4,7':(8,4), '5,4':(8,4), '11,0':(7,4),
             '2,2':(7,4), '2,4':(6,5), '13,6':(10,2), '5,0':(5,6)}
levels = {}
for key, n in DUNGEON.items():
    sc, sr = map(int, key.split(','))
    tx, ty = LEVELTILE[key]
    how = 'open'
    for k, v in list(caves.items()):
        if v['sc'] == sc and v['sr'] == sr:
            how = v['how']; tx, ty = v['tx'], v['ty']
            del caves[k]
    levels[str(n)] = {'col':sc, 'row':sr, 'tx':tx, 'ty':ty, 'how':how}

# ---- attach each icon to its nearest entrance ----
def entpix(v): return (v['sc'] * 256 + v['tx'] * 16 + 8, v['sr'] * 176 + v['ty'] * 16 + 8)

# the "LEVEL-n" label boxes on the map contain heart / triforce icons, so any
# hit that lands on a level's own screen is a label, not a cave's contents
def on_level_screen(hx, hy):
    return '%d,%d' % (hx // 256, hy // 176) in DUNGEON

claimed = {}
for icon, item in ICON_ITEM:
    for hx, hy in hits.get(icon, []):
        if on_level_screen(hx, hy): continue
        best, bd = None, 10 ** 9
        reach = 420 if item in ('swordMagic','swordWhite','swordWood','letter','takeOne') else 250
        for k, v in caves.items():
            if k in claimed: continue
            ex, ey = entpix(v)
            d = (ex - hx - 8) ** 2 + (ey - hy - 8) ** 2
            if d < bd: bd, best = d, k
        if best is not None and bd <= reach * reach:
            claimed[best] = item

# Anything with no icon becomes an old man, a toll or a gift, which is what the
# large majority of plain caves in the original hold.
ROTATE = ['hint','gift30','payDoor','hint','gamble','gift100','hint','payDoor']
out = {}
for i, (k, v) in enumerate(sorted(caves.items())):
    v['id'] = claimed.get(k, ROTATE[i % len(ROTATE)])
    out[k] = v

hdr = '''/* ============================================================================
   THE AJAX ADVENTURE - ow-secrets.js
   Every overworld entrance: where it is, how it opens, and what is behind it.
   Generated by _tools/extract-secrets.py - do not hand-edit.
   ========================================================================== */
(function (global) {
'use strict';
global.EQ = global.EQ || {};
global.EQ.OW_SECRETS =
'''
open(os.path.join(ROOT, 'js', 'ow-secrets.js'), 'w').write(
    hdr + json.dumps({'levels': levels, 'caves': out}, indent=0, separators=(',', ':'))
    + ';\n})(window);\n')

print('levels:', {k: (v['col'], v['row'], v['how'])
                  for k, v in sorted(levels.items(), key=lambda x: int(x[0]))})
print('caves:', len(out))
print('contents:', Counter(v['id'] for v in out.values()))
print('methods :', Counter(v['how'] for v in out.values()))
print('identified by icon:', len(claimed))
