"""Read the overworld's creatures off the labelled Quest-1 map.

Every overworld tile's true graphic is known (tile id map + the tile sheet), so
anything on the map that is NOT the expected tile is something drawn on top:
a creature, an item icon, a marker box or a text label. Compact clumps of the
right size are the creatures; wide clumps are text and are dropped.

Run:  SCRATCH=<dir with ow_labeled.png, overworldtiles.png,
                    nes_zelda_overworld_tile_map.txt> python3 extract-ow-enemies.py
"""
import json, os
from collections import Counter
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
SC   = os.environ.get('SCRATCH', '.')
OFF  = 256

lab   = Image.open(os.path.join(SC, 'ow_labeled.png')).convert('RGB'); lp = lab.load()
sheet = Image.open(os.path.join(SC, 'overworldtiles.png')).convert('RGB'); sp = sheet.load()
SW, SH = sheet.size
tm = [l.split() for l in
      open(os.path.join(SC, 'nes_zelda_overworld_tile_map.txt')).read().splitlines()]

MARKER = {(255,0,0), (255,47,0), (0,255,0), (0,42,255)}

cache = {}
def tile(h):
    if h in cache: return cache[h]
    i = int(h, 16); r, c = divmod(i, 20)
    x0, y0 = c * 17 + 1, r * 17 + 1
    cache[h] = None if (x0 + 16 > SW or y0 + 16 > SH) else \
               [[sp[x0 + x, y0 + y] for x in range(16)] for y in range(16)]
    return cache[h]

out = {}
for sr in range(8):
    for sc in range(16):
        # mask of pixels that differ from the expected terrain
        diff = [[False] * 256 for _ in range(176)]
        for ty in range(11):
            for tx in range(16):
                img = tile(tm[sr * 11 + ty][sc * 16 + tx])
                if img is None: continue
                for y in range(16):
                    for x in range(16):
                        px = lp[OFF + sc * 256 + tx * 16 + x, sr * 176 + ty * 16 + y]
                        if px != img[y][x] and px not in MARKER:
                            diff[ty * 16 + y][tx * 16 + x] = True

        seen = set(); found = []
        for y in range(176):
            for x in range(256):
                if not diff[y][x] or (x, y) in seen: continue
                stack = [(x, y)]; blob = []
                while stack:
                    ax, ay = stack.pop()
                    if (ax, ay) in seen: continue
                    if ax < 0 or ay < 0 or ax >= 256 or ay >= 176: continue
                    if not diff[ay][ax]: continue
                    seen.add((ax, ay)); blob.append((ax, ay))
                    for dx, dy in ((1,0),(-1,0),(0,1),(0,-1),(1,1),(-1,-1),(1,-1),(-1,1)):
                        stack.append((ax + dx, ay + dy))
                if not (40 <= len(blob) <= 320): continue
                bx = [b[0] for b in blob]; by = [b[1] for b in blob]
                w, h = max(bx) - min(bx), max(by) - min(by)
                if w > 20 or h > 20 or w < 6 or h < 6: continue   # text is wide, dust is small
                cc = Counter(lp[OFF + sc * 256 + a, sr * 176 + b] for a, b in blob)
                found.append([min(bx), min(by), list(cc.most_common(1)[0][0])])
        if found: out['%d,%d' % (sc, sr)] = found

tot = sum(len(v) for v in out.values())
cols = Counter(tuple(c) for v in out.values() for _, _, c in v)
print('screens with creatures:', len(out), ' creatures:', tot)
print('colours:', cols.most_common(14))

hdr = '''/* ============================================================================
   THE AJAX ADVENTURE - ow-enemies.js
   Which creatures stand on each overworld screen, and where, read off the
   labelled Quest-1 map by diffing it against the known terrain graphics.
   Each entry is [pixelX, pixelY, [r,g,b]]; species is inferred from colour.
   Generated by _tools/extract-ow-enemies.py - do not hand-edit.
   ========================================================================== */
(function (global) {
'use strict';
global.EQ = global.EQ || {};
global.EQ.OW_ENEMIES =
'''
open(os.path.join(ROOT, 'js', 'ow-enemies.js'), 'w').write(
    hdr + json.dumps(out, separators=(',', ':')) + ';\n})(window);\n')
print('wrote js/ow-enemies.js', os.path.getsize(os.path.join(ROOT, 'js', 'ow-enemies.js')))
